baseurl = "https://odnualam.com/"
title = "Fransiscus Rolanda Malau"
copyright = "Copyright &copy; 2022 - Fransiscus Rolanda Malau"
canonifyurls = true
theme = "hugo-kiera"

paginate = 12

summaryLength = 10
enableEmoji = true
pygmentsCodeFences = true

#disqusShortname = "myShortName"

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    #name = "Example"
    github = "odnualam"
    #gitlab = "username"
    linkedin = "odnualam"
    #facebook = "username"
    twitter = "odnualam"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname
    #devto = "username"

[params]
    tagline = "It always seems impossible until it’s done."
    description = "Fransiscus Rolanda Malau: It always seems impossible until it’s done."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = []  #Optional Customised CSS
    #favicon = ""
    #utterancesRepo = "username/repository"
    #utterancesIssueTerm = "pathname"
    #homepageLength = 10
    #commentAutoload = true  #This mean reader don't need click, disqus comment autoload
    #mathjax = true #Enable display of mathematics using mathjax (LaTeX syntax)
    #katex = true #Enable display of mathematics using katex (Faster LaTeX rendering)
    #google_fonts = ["Staatliches"] # Adds additional google fonts
    #disableDarkModeCSS = false # disables css style for users using dark-mode

[[menu.main]]
  identifier = ""
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts"
  weight = 3

[[menu.main]]
  identifier = "uses"
  name = "Uses"
  url = "/uses"
  weight = 4